4 leen status aanpassen
ACI-Rental/front-end pull request #33
Opened 2021-06-07 11:59 UTC by Pigna

2021-06-07 12:27 UTC, SieBrum requested changes

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.scss
> +    .main-container-reservations {
indenting/formatting in deze file klopt niet

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +  selector: 'app-app-reservation-action-page',
app-app

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +  reservations: Array<IReservationProduct> = [
Test gegevens

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +    if (id > 0) {
Kan een ID niet 0 zijn in de db?

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +            //statements;
todo?

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +      this.snackbarService.open(this.translate.instant('RESERVATION.ACTION.UNSUCCESSFUL'), undefined, {
showErrorNotification functie

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +import { IProductFlat } from '../models/product-flat.model';
ongebruikt

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +import { Router } from '@angular/router';
ongebruikt

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +    private router: Router,
ongebruikt

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +    if (id && parseInt(id))
miss redirecten naar een andere pagina als dit mist?

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.scss
> +            .itemBox-imgbox{
hoofdletters mogen niet in SCSS (of css in het algemeen) classes. 
Dit wordt dus `item-box-imgbox` (of anders)
Vergeet niet dan ook de HTML aan te passen :p

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +      this.snackbarService.open(this.translate.instant('RESERVATION.ACTION.UNSUCCESSFUL'), undefined, {
Deze vertaling bestaat niet vgsmij

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +          this.snackbarService.open(this.translate.instant('RESERVATION.ACTION.SUCCESS'), undefined, {
Deze vertaling bestaat niet vgsmij

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +            this.showErrorNotification('RESERVATION.PRODUCT.ERROR');
Deze vertaling bestaat niet vgsmij

2021-06-07 12:27 UTC, SieBrum commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +          this.showErrorNotification('RESERVATION.NO_RESPONSE_DATA');
Deze vertaling bestaat niet vgsmij

2021-06-07 13:14 UTC, Pigna commented on src/app/app-reservation-action-page/app-reservation-action-page.component.ts
> +    if (id > 0) {
Key begint standaard bij 1

2021-06-08 08:17 UTC, SieBrum approved these changes

2021-06-08 08:17 UTC, SieBrum commented
LGTM

2021-06-08 08:17 UTC, merged